### ISSUE TITLE
AppHostWebhookEventSink runs on same thread as IWebhooks.Publish()

### ISSUE THREAD

**Issue by jezzsantos** [jezzsantos/ServiceStack.Webhooks#1]
Because `AppHostWebhookEventSink` runs on the same thread as `IWebhooks.Publish()` **all events** raised by my service operations are going to be relayed to **all subscribers** before my service operation can process the incoming request. This means that my service operation could either:

* timeout (i.e. waiting for subscribers endpoints to respond) or 
* timeout waiting to retry (default 3 times) sending to subscriber endpoints, or 
* at the very least slow down my service endpoint waiting until all subscribers are notified. 

It is a perf killer!

**Comment by jezzsantos** [comment]
This is true indeed!, and without trying to sound pious about it, was exactly how we designed it.

The initial design goals of `AppHostWebhookEventSink` were:
* to create a default implementation of `IWebhookEventSink` that would work immediately after adding the `WebhookFeature`, and
* not require any other architectural components that would be needed end-to-end to connect the raising of events (`IWebhooks.Publish()`) to the relaying of events to subscribers. (i.e. async, queues, buses, etc.) Hence why it relays events in-proc with the service that published them.
* Create an end-to-end component that would suffice for integration testing, where it is easier to test sync functionality, rather than waiting for async processes to complete.
* Create an end-to-end component to speed peoples uptake of the `WebhookFeature`, so that they can immediately start to see all the pieces working, they can quickly experiment with them, and they can more quickly think about operations of their service, and how to mitigate deployment issues sooner than later. (i.e. buys them time so they can to step back and see the big picture).

To mitigate developers that use the `WebhookFeature` experiencing any of the perf issues (in real production systems) outlined in the OP, we have made very explicit warnings all across the docs recommending that they don NOT use this component in production systems, for the very reasons outlined above, AND to find a Sink that would fit their distributed architecture better.

Next Steps
====

If the initial design goals are not right, and if users of the 'WebookFeature' find this still to be a significant issue, show stopper, or a serious usability issue, we could take one of the following actions:

1. We _could_ rename `AppHostWebhookEventSink` to `TestAppHostWebhookEventSink` (or some such name) to reveal its true intention. 
2. We could modify the existing `AppHostWebhookEventSink` to relay events on a background thread by default, AND/OR provide a setting that gives the developer the choice of async or sync relaying (i.e. `bool RelayAsync { get; set; }`). The idea being that `RelayAsync=true` for production use and `RelayAsync = false` for debugging or testing. We would need to be crystal clear with developers that relaying messages "async" would be tying up threads of their service that would otherwise be ready for incoming requests.
3. We could rip out the `AppHostWebhookEventSink` all together, and not deliver one out of the box when the `WebhookFeature` is installed. That would mean that it would be _far_ harder for developers to get started with `ServiceStack.Webhooks` package, since (1) the whole thing would not do anything the  moment they try to use it, (b) they would then (had they read the docs) discover that they would need to either code up their own `IWebhookEventSink` and wire it in, or they could install another nuget package that had one (i.e. `ServiceStack.Webhooks.Azure` etc), and then configure that relay mechanism (and its infrastructure) as well as to wire it into feature. Before they see the whole thing working end-to-end.

What else could we do?

**Comment by georgehemmings** [comment]
The current design makes sense to me. I think the explicit warnings are good enough.

Would a [Hangfire](http://hangfire.io/) sink be a good addition? This would handle the heavy lifting of handling background ASP.NET processing.

**Comment by jezzsantos** [comment]
Hey @georgehemmings, thanks for jumping in.

I am not familiar with Hangfire in practice. If you are, does hangfire boil down to using another ASP.NET thread to do work on (since it claims "No Windows Service or separate process required")? 

If so, we are kind of back to deciding whether we should to try and fix the `AppHostEventSink` to make it do the right thing for performance, or alternatively not do that, and strengthen its position as a test sink instead?

I'm good either way, its really what people want to do it.
Of course, we can always do both, and go with a option 2 above?

What do you think?

**Comment by georgehemmings** [comment]
I think leaving `AppHostEventSink` as the default is best for the reasons you stated above. 

Trying to make `AppHostEventSink` production worthy might not be realistic. I've never tried but I've [read](http://haacked.com/archive/2011/10/16/the-dangers-of-implementing-recurring-background-tasks-in-asp-net.aspx/) that there is more to it than just run on another thread. Even if you do crack that bit, you'd need to introduce some kind of persistence for reliability. You might end up reinventing the wheel.

**Comment by jezzsantos** [comment]
Yep, exactly. Not sure I wanted to go there at all... 

Lots of developers get very nervous about taking up other request threads, so I am good avoiding the whole issue. Saw the same thing over at [Serilog.Async](https://github.com/serilog/serilog-sinks-async)
I'd rather direct them to some reliable delivery mechanism like queues, etc (as we do over at [ServiceStack.Webhooks.Azure](https://github.com/jezzsantos/ServiceStack.Webhooks.Azure))
