### ISSUE TITLE
ServiceStack.Webhooks.Signed

### ISSUE THREAD

**Issue by jezzsantos** [jezzsantos/ServiceStack.Webhooks#10]
Need a (additional) signed version of the nuget packages:

* ServiceStack.Webhooks
* ServiceStack.Webhooks.Interfaces
* ServiceStack.Webhooks.OrmLite

i.e.:
* ServiceStack.Webhooks.Signed
* ServiceStack.Webhooks.Interfaces.Signed
* ServiceStack.Webhooks.OrmLite.Signed

using a \*.snk file in the solution

**Comment by jezzsantos** [comment]
To build both flavors of the packages (a signed one and an unsigned one), I guess, I need to:

* Add an \*.snk to the solution
* Add another \*.nuspec file in the project (for the \*.Signed version)
* Muck about with the MSBUILD targets that builds \*nuspec files (in BuildConfiguration,targets), to generate the new files
* As well as bind to ServiceStack.\*.Signed or ServiceStack.\* assemblies???

I think perhaps I just have a \*Signed.csproj and \*.Signed.nspec for each of the projects (where the \*.Signed.csproj version contains the references to the ServiceStack.\*.Signed.assemblies), and let the existing tooling do the work

**Comment by jezzsantos** [comment]
@mythz Can I draw upon your experiences here?

I think all I want to do is support people who want to use this nuget in their solution where they have decided to sign their own assemblies. It is a lot less about actually securing the signing key (which we will assume will be in the repo anyway).

I see two choices:

1) Create two versions of each nuget, one that is: 'ServiceStack.Webhooks' and 'ServiceStack.Webhooks.Signed' and publish both. (of course they will have to reference ServiceStack or ServiceStack.Signed respectively)
2) Just sign the assemblies in 'ServiceStack.Webhooks' package with the *.snk , and move on.

Is there some disadvantage to (2) above?

**Comment by mythz** [comment]
Well I'm in the camp of wishing strong naming never existed so I've split it out into 2 discrete packages so strong naming never affects the majority of customers who don't care for it. 

I only created .Signed packages for the popular packages upon request so my thoughts are only create a .Signed version if there's demand for it.

**Comment by jezzsantos** [comment]
Understood.

I have demand for it, so no its a question of what to do. either option (1) or option (2) above.

I wanted to see what you though of just going with a signed version as the default, and not bother to put that in the name at all (i.e. keep it ServiceStack.Webhooks).

**Comment by mythz** [comment]
My choice is still with option 3) YAGNI - Only create 1 unsigned version :)

**Comment by jezzsantos** [comment]
Yes, yes, YAGNI, but its been asked for now! 

I am not seeing a downstream problem with just doing option (2).

**Comment by jezzsantos** [comment]
I think you must sign the ServiceStack.Interfaces project eh?

**Comment by mythz** [comment]
Yeah [had to](http://docs.servicestack.net/releases/v4.0.0#servicestackinterfaces-is-now-strong-named).

**Comment by jezzsantos** [comment]
OK, so I have a solution built on the "signed" branch in [this commit](https://github.com/jezzsantos/ServiceStack.Webhooks/commit/8cac787d891c1ae7e3acc7fcfc91d6c0794f5a6a)

Its not deployed yet, but its is ready to go. We just have to decide to go with it, or not, and pull the trigger to merge it to master.

* It uses separate \*.csproj files for the Signed assembly versions, and MSBUILD properties to sign the assemblies for those projects.
* It is all automated.

The only crappy part here, is that we have duplicate \*.csproj files and duplicate package.config files, which would need to be kept in sync whenever a new code file or nuget is introduced into the project. 

Which really sucks. I wish I knew a way to help use maintain that stuff so we don't forget to maintain both project files.

**Comment by mythz** [comment]
> Which really sucks. I wish I knew a way to help use maintain that stuff so we don't forget to maintain both project files.

FYI I use a shortcut key to run this [node script](https://github.com/ServiceStack/ServiceStack/blob/master/build/codegen-projs.js) that generates all Signed projects from their original csproj.

**Comment by jezzsantos** [comment]
Nice idea! thanks

**Comment by jezzsantos** [comment]
OK, OK.

After all this work. Now I am thinking WTF!

> Why not just sign all the damn assemblies?

We already do SemVer style versioning, so the actual `AssemblyVersion` wont ever change from being 1.0.0.0 (for the foreseeable future)

From `GlobalAssemlyInfo.cs`:
```
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.5.2")]
[assembly: AssemblyInformationalVersion("1.5.2")]
```

* If the assemblies are all signed, then consumers won't have a problem if either they need signed or unsigned.
* The nuget versioning problem is largely mitigated with SemVer and fixed `AssemblyVersion`

What gives with this solution? 
Who am I actually stitching up [setting up for failure] if we do this?

**Comment by mythz** [comment]
Sign them if you want, but Unsigned projects don't have strong naming issues which other than having no good reason to exist is why I avoid them where possible. But if you pin the AssemblyVersion you should mitigate a lot of the issues.

**Comment by jezzsantos** [comment]
Thanks @mythz, I'm between a rock and a hard place right now, and need to make a decision.

As far as I can tell signing the damn things and pinning the `AssemblyVersion` number, and Keeping 'Signed' out of the package name seems like a good first move.

If it comes to it, later I can create two versions of the packages, and call one ".Signed", as is commonly done.

**Comment by georgehemmings** [comment]
@jezzsantos this had messed things up a bit for me. I reference the unsigned SS packages. Now ServiceStack.Webhooks has a dependency on ServiceStack.Signed, I'm ending up with both ServiceStack.Signed and ServiceStack in my packages.config.

I think it would be better to split the Signed packages off so they fit better with SS.

**Comment by jezzsantos** [comment]
OK, but first in the spirit of YAGNI, is it too hard to change from ServiceStack to ServiceStack.Signed do you think for our customers? (The way to do it is simply:

1. Open the `packages.config` file and change all the ServiceStack packages to ServiceStack.Signed packages. repeat for other SS packages
2. Then in the Nuget Package Manager Console you do a: `Update-Package ServiceStack.Signed -reinstall`, repeat for other SS packages.

Nuget does the hard work for you and gets rid of the old references.

We **can** do both kinds of packages (as we can see in 8cac787), but it puts a significant maintenance burden on the project (duplicate project files). But that's better than the burden on our customers.

Let me know what you think.

**Comment by georgehemmings** [comment]
I'm in the anti-signed camp ;)

More practically, the problem is that some of the plugins I'm using don't have signed versions. They have dependencies on non-signed SS.

**Comment by jezzsantos** [comment]
OK, well, then we are going to have to support both. PITA
Ill get it done next, and take down v1.6.0
