### ISSUE TITLE
ServiceStack Latest v5.9 giving issue with ServiceStack.Webhooks v3.0.1

### ISSUE THREAD

**Issue by sagar-ashok-mahajan** [jezzsantos/ServiceStack.Webhooks#18]
I am trying to use Webhook plugin with  ServiceStack v5.9 but with latest  ServiceStack.Webhooks v3.0.1 giving me issue, please refer error below:

`    {
  "responseStatus": {
    "errorCode": "MissingMethodException",
    "message": "Method not found: 'Int32 ServiceStack.OrmLite.OrmLiteWriteExpressionsApi.Delete(System.Data.IDbConnection, System.Linq.Expressions.Expression`1<System.Func`2<!!0,Boolean>>)'.",
    "stackTrace": "[DeleteSubscription: 6/15/2020 12:42:28 PM]:\n[REQUEST: {id:c42c28e2-f432-40d1-b370-49a5a8506035}]\r\nSystem.MissingMethodException: Method not found: 'Int32 ServiceStack.OrmLite.OrmLiteWriteExpressionsApi.Delete(System.Data.IDbConnection, System.Linq.Expressions.Expression`1<System.Func`2<!!0,Boolean>>)'.\r\n   at ServiceStack.Webhooks.OrmLite.OrmLiteSubscriptionStore.Delete(String subscriptionId)\r\n   at ServiceStack.Webhooks.ServiceInterface.SubscriptionService.Delete(DeleteSubscription request)\r\n   at lambda_method(Closure , Object , Object )\r\n   at ServiceStack.Host.ServiceRunner`1.<ExecuteAsync>d__15.MoveNext() in C:\\BuildAgent\\work\\3481147c480f4a2f\\src\\ServiceStack\\Host\\ServiceRunner.cs:line 133\r\n",
    "errors": []
  }
}`

Upon contacting ServiceStack it is advice to raise issue with you to provide new version that targets the latest v5.9.

Reference: https://stackoverflow.com/questions/62388956/servicestack-webhook-servicestack-webhooks-ormlite-subscription-store-plugin-i

**Comment by jezzsantos** [comment]
Hi @sagar-ashok-mahajan  Are you simply asking for a version bump Of ServiceStack to 5.9?

**Comment by jezzsantos** [comment]
You could just submit a PR with that change and I will merge it, as the quickest way forward. I cant get to this for a day or so.

**Comment by sagar-ashok-mahajan** [comment]
Hi Team,

May be answer is yes, when I contact ServiceStack support they responsed:


"You have a version mismatch with the version of ServiceStack you're trying to use vs the ServiceStack version that the ServiceStack.Webhooks.OrmLite<https://www.nuget.org/packages/ServiceStack.Webhooks.OrmLite> NuGet package is built with.

You should raise an issue with the jezzsantos/ServiceStack.Webhooks<https://github.com/jezzsantos/ServiceStack.Webhooks> GitHub project to release a new version that targets the latest v5.9.

Otherwise you will need to downgrade to use ServiceStack v5.5.0 that the NuGet package was built with."


Please let me know if anything I can do from my side.


Thanks,

Sagar Mahajan

________________________________

**Comment by jezzsantos** [comment]
Released in version 3.1.0
