### ISSUE TITLE
About using HMAC SHA-1 and HMAC SHA-256 in X-HUB-SIGNATURE header

### ISSUE THREAD

**Issue by bruke291** [jezzsantos/ServiceStack.Webhooks#25]
Hello everyone,

I apologize if this causes any inconvenience. I have a question: I read the [Subscriber Security](https://github.com/jezzsantos/ServiceStack.Webhooks/wiki/Subscriber-Security) documentation. In the document, it describes that the ServiceStack Webhook library uses the HMAC algorithm to create a signature in the X-HUB-SIGNATURE header. However, when I checked the library's code, it actually uses the HMAC SHA-256 algorithm, but the header indicates that the value starts with "sha1=". Even the description of the CreateHmacSignature function in the [HmacUtils class](https://github.com/jezzsantos/ServiceStack.Webhooks/blob/master/src/Webhooks.Interfaces/Security/HmacUtils.cs) states that the function returns a value calculated using the HMAC algorithm based on [RFC3174](https://www.rfc-editor.org/rfc/rfc3174) (which refers to the use of SHA-1). I have searched through the release notes and reviewed the git history, but I couldn't find any useful information regarding this discrepancy. I would really like to understand why the documentation and the header indicate the use of SHA-1, but SHA-256 is actually being used. Could anyone please clarify or provide any available information?

Thank you very much.

**Comment by jezzsantos** [comment]
I think this is just an implementation mistake, and that the `sha1=` part should really be just `sha256=` simple as that.

**Comment by bruke291** [comment]
> I think this is just an implementation mistake, and that the `sha1=` part should really be just `sha256=` simple as that.

Oh, thank you for your support in helping me :D.
